### ISSUE TITLE
nfd-status does not work

### ISSUE THREAD

**Issue by felixrabe** [felixrabe-attic/named-data-education--ndn-with-docker#1]
The Docker-based installation method described below currently fails with the following error:

```
felix-mba:docker-images fr$ docker run --rm -ti nfd
root@cb92f60fb4c0:/# nfd-start
root@cb92f60fb4c0:/# nfd-status
ERROR: error while connecting to the forwarder (No such file or directory)
```

**Comment by al3x** [comment]
@felixrabe: I'd be happy to try to fix your Docker issue, but it would be easier if we could keep the work consolidated in this repository. There are currently no files in the repo, so I can't clone or fork it. Could you please check in the `docker.md` file that you posted to the ndn-interest mailing list as `README.md`, as a starting point?

**Comment by felixrabe** [comment]
Done.

**Comment by yoursunny** [comment]
It's reported that this Bug is caused by [NFD Bug 2013](http://redmine.named-data.net/issues/2013).
Bug 2013 is fixed now. Please verify.

**Comment by felixrabe** [comment]
@al3x In your commit, you start `nfd` directly. Does `nrd` not also need to be run?

**Comment by al3x** [comment]
@felixrabe I'm not sure. I don't know the whole NDN stack.

**Comment by felixrabe** [comment]
Sorry @yoursunny the missing dependencies are for the Debian-based build.

I'll start new GitHub issues with each separate problem. (And Redmine issues for whatever makes sense of course.)

**Comment by felixrabe** [comment]
The specific issue of `nfd-status` not working is (most likely) caused by the `nfd` package not installing properly – see #3.

**Comment by felixrabe** [comment]
The missing dependencies issue is about documenting the source build process for Debian – see #4.
